<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.3</version>
    </parent>
    <groupId>com.example</groupId>
    <artifactId>backend-springboot</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>backend-springboot</name>
    <description>Demo project for Spring Boot</description>
    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <com.sap.xs.auditlog.audit-java-client.version>2.0.21</com.sap.xs.auditlog.audit-java-client.version>
        <sap.cloud.security.version>2.17.5</sap.cloud.security.version>
        <com.sap.cloud.sjb.xs-env.version>1.54.0</com.sap.cloud.sjb.xs-env.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.3.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sap.xs.auditlog</groupId>
            <artifactId>audit-java-client-api</artifactId>
            <version>${com.sap.xs.auditlog.audit-java-client.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sap.xs.auditlog</groupId>
            <artifactId>audit-java-client-impl</artifactId>
            <version>${com.sap.xs.auditlog.audit-java-client.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sap.cloud.security.xsuaa</groupId>
            <artifactId>token-client</artifactId>
            <version>${sap.cloud.security.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.sap.cloud.sjb</groupId>
            <artifactId>xs-env</artifactId>
            <version>${com.sap.cloud.sjb.xs-env.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.sap.cp.security</groupId>
            <artifactId>resilient-auditlog-client</artifactId>
            <version>1.91.0</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>sap-public-repo</id>
            <url>https://maven.sap.com/repository/public</url>
        </repository>
    </repositories>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>